### ISSUE TITLE
Problems setting up on new raspian

### ISSUE THREAD

**Issue by williamwithin** [MakerLabsVan/Rotary-Phone-Player#1]
I'm trying to set this up again for MOV, due to corrupted SD card.

First issue is that the omxwrapper submodule on your repo is not found:

`fatal: No url found for submodule path 'omxwrapper/python-omxplayer-wrapper' in .gitmodules`

I can get around that by installing omxwrapper and its' dependencies via `pip install`

The next issue is this error:

`SystemError: DBus cannot connect to the OMXPlayer process`

There is a note on the readme file to "comment out an exception raised in the OMXplayer". I have tried to do that but I'm not sure what to comment out. 

Any suggestions on how to get this to work appreciated.

**Comment by derekgaw** [comment]
Hi William,

Looking at the source code here (https://python-omxplayer-wrapper.readthedocs.io/en/latest/_modules/omxplayer/player/), I'd try replacing the line:        

raise SystemError('DBus cannot connect to the OMXPlayer process')

with:

// raise SystemError('DBus cannot connect to the OMXPlayer process')

Please let us know if that resolves the issue.

**Comment by derekgaw** [comment]
Better link to the file/line: https://github.com/willprice/python-omxplayer-wrapper/blob/625a396d1108a6c9138150645606f5564684c04f/omxplayer/player.py#L223

**Comment by williamwithin** [comment]
Thank you for the suggestion.

The python comment character should be `#` not `//` so I changed line 223 of player.py to:

`# raise SystemError('DBus cannot connect to the OMXPlayer process')`

But that has not solved the issue. As before the change to player.py, when the pi boots up, the dialtone is played twice and that's it.

The error in the log now shows:

`dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)`

**Comment by williamwithin** [comment]
Here is the full log:

> Traceback (most recent call last):
>   File "rotary-test-4.py", line 99, in <module>
>     player.play()
>   File "</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-94>", line 2, in play
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 48, in wrapped
>     return fn(self, *args, **kwargs)
>   File "</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-93>", line 2, in play
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 85, in wrapped
>     return from_dbus_type(fn(self, *args, **kwargs))
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 780, in play
>     if not self.is_playing():
>   File "</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-90>", line 2, in is_playing
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 48, in wrapped
>     return fn(self, *args, **kwargs)
>   File "</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-89>", line 2, in is_playing
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 85, in wrapped
>     return from_dbus_type(fn(self, *args, **kwargs))
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 752, in is_playing
>     self._is_playing = (self.playback_status() == "Playing")
>   File "</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-28>", line 2, in playback_status
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 48, in wrapped
>     return fn(self, *args, **kwargs)
>   File "</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-27>", line 2, in playback_status
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 85, in wrapped
>     return from_dbus_type(fn(self, *args, **kwargs))
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 367, in playback_status
>     return self._player_interface_property('PlaybackStatus')
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 829, in _player_interface_property
>     return self._interface_property(self._player_interface.dbus_interface, prop, val)
>   File "/usr/local/lib/python2.7/dist-packages/omxplayer/player.py", line 823, in _interface_property
>     return self._properties_interface.Get(interface, prop)
>   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
>     **keywords)
>   File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
